// Generated by scripts/build-prompt-bundle.cjs. Do not edit.
export const EASY_CODE_RUNTIME_VERSION = "0.1.0" as const;
export const PACKAGED_PROMPT_BUNDLE_VERSION = "1.2.1" as const;
export const PACKAGED_PROMPT_BUNDLE_MANIFEST_HASH = "sha256:60558602c1dad9fa9b0d8a329ef79829a65d179cf98c3a05601e364b21a0f5af" as const;
