// Generated by scripts/build-prompt-bundle.cjs. Do not edit.
export const EASY_CODE_RUNTIME_VERSION = "0.1.0" as const;
export const PACKAGED_PROMPT_BUNDLE_VERSION = "1.2.1" as const;
export const PACKAGED_PROMPT_BUNDLE_MANIFEST_HASH = "sha256:c86cd4206573b10a5efb9cf040493f8a2258a4f402e302034d1aeae6969b9b04" as const;
