// Generated by scripts/build-prompt-bundle.cjs. Do not edit.
export const EASY_CODE_RUNTIME_VERSION = "0.1.0" as const;
export const PACKAGED_PROMPT_BUNDLE_VERSION = "1.2.1" as const;
export const PACKAGED_PROMPT_BUNDLE_MANIFEST_HASH = "sha256:3ad8a33fd79eafd42220828efb330573d5a4108fc45b6b2bd92ec037a5726d7e" as const;
